Repository atomist/cli, pull requests merged in 2018-08, with the labels that each got.

#7 Add modules to fix link compilation
  lib/typings/index.ts
Labels: atomist:merge-on-approve

#26 Print more version information in --version
  lib/version.ts
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#24 Remove deprecated scripts
  bin/postInstall.d.ts
  bin/postInstall.js.map
  package.json
Labels: auto-merge:on-approve, changelog:removed
