Repository atomist/cli, pull requests merged in 2019-09, with the labels that each got.

#110 Remove broken, deprecate outdated commands
  index.ts
  lib/command.ts
  lib/install.ts
  lib/kube.ts
  lib/workspace.ts
  package-lock.json
  package.json
  test/command.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:deprecated, changelog:removed

#116 Add `--dev` and `--debug` flag to start command
  index.ts
  lib/repositoryStart.ts
  lib/spawn.ts
  lib/start.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added, enhancement

#118 Apply target for @atomist/sdm-pack-k8s
  package-lock.json
  package.json
Labels: auto-branch-delete:on-close, auto-merge-method:squash, auto-merge:on-approve
